import random
import time
from winsound import Beep

def RP():
    print("Would you like to RP?")
    answer = raw_input("Y/N:")
    print("I take off my shirt to reveal my massive, robust pecs.")
    print("Would you like to continue?")
    answer = raw_input("Y/N:")
    print("I take off my pants, to reveal my massive, robust thighs.")
    print("Would you like to continue?")
    answer = raw_input("Y/N:")
    print("I take off your shirt and remove some lint from your belly button.")
    print("Would you like to continue?")
    answer = raw_input("Y/N:")
    print("I put the tiny lint into a small vial.")
    print("Would you like to continue?")
    answer = raw_input("Y/N:")
    print("I move a small lamb from behind a small tree.")
    print("Would you like to continue?")
    answer = raw_input("Y/N:")
    print("I pet the small lamb.")
    print("Would you like to continue?")
    answer = raw_input("Y/N:")
    print("I stare into your eyes.")
    print("Would you like to continue?")
    answer = raw_input("Y/N:")
    print("The small lamb starts to yell")
    Beep(1000,100)